
version: '3.9'

services:
  chessterisk:
    image: chessterisk:latest
    ports:
      - '80:5000'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: chessterisk
      POSTGRES_PASSWORD: chessterisk
